---
- hosts: all
  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: true
      become: true
      become_method: su
      when: ansible_os_family == "Debian"

    - name: Ensure sudo Package is Installed
      apt:
        name: sudo
        state: present
      become: true
      become_method: su
      when: ansible_os_family == "Debian"
